/*
 * RemapDB REST API Documentation
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains. 
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import EngineEcu from './EngineEcu';
import EnginePerformance from './EnginePerformance';
import EngineTcu from './EngineTcu';
import EngineTuning from './EngineTuning';

/**
 * The EngineWTuning model module.
 * @module model/EngineWTuning
 * @version 1
 */
export default class EngineWTuning {
  /**
   * Constructs a new <code>EngineWTuning</code>.
   * Engine object
   * @alias module:model/EngineWTuning
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EngineWTuning</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EngineWTuning} obj Optional instance to populate.
   * @return {module:model/EngineWTuning} The populated <code>EngineWTuning</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EngineWTuning();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('engine_code'))
        obj.engineCode = ApiClient.convertToType(data['engine_code'], 'String');
      if (data.hasOwnProperty('year'))
        obj.year = ApiClient.convertToType(data['year'], 'Number');
      if (data.hasOwnProperty('capacity'))
        obj.capacity = ApiClient.convertToType(data['capacity'], 'Number');
      if (data.hasOwnProperty('cylinders'))
        obj.cylinders = ApiClient.convertToType(data['cylinders'], 'Number');
      if (data.hasOwnProperty('engine_type'))
        obj.engineType = ApiClient.convertToType(data['engine_type'], 'String');
      if (data.hasOwnProperty('fuel'))
        obj.fuel = ApiClient.convertToType(data['fuel'], 'String');
      if (data.hasOwnProperty('ecus'))
        obj.ecus = ApiClient.convertToType(data['ecus'], [EngineEcu]);
      if (data.hasOwnProperty('tcus'))
        obj.tcus = ApiClient.convertToType(data['tcus'], [EngineTcu]);
      if (data.hasOwnProperty('performance'))
        obj.performance = EnginePerformance.constructFromObject(data['performance']);
      if (data.hasOwnProperty('tuning'))
        obj.tuning = EngineTuning.constructFromObject(data['tuning']);
    }
    return obj;
  }
}

/**
 * Engine ID.
 * @member {Number} id
 */
EngineWTuning.prototype.id = undefined;

/**
 * Engine name.
 * @member {String} name
 */
EngineWTuning.prototype.name = undefined;

/**
 * URL-friendly name (slug).
 * @member {String} slug
 */
EngineWTuning.prototype.slug = undefined;

/**
 * Engine code.
 * @member {String} engineCode
 */
EngineWTuning.prototype.engineCode = undefined;

/**
 * Year of manufacture.
 * @member {Number} year
 */
EngineWTuning.prototype.year = undefined;

/**
 * Engine capacity in cubic cm.
 * @member {Number} capacity
 */
EngineWTuning.prototype.capacity = undefined;

/**
 * Number of cylinders.
 * @member {Number} cylinders
 */
EngineWTuning.prototype.cylinders = undefined;

/**
 * Engine type.
 * @member {String} engineType
 */
EngineWTuning.prototype.engineType = undefined;

/**
 * Name of the fuel.
 * @member {String} fuel
 */
EngineWTuning.prototype.fuel = undefined;

/**
 * List of ECU's used in this engine.
 * @member {Array.<module:model/EngineEcu>} ecus
 */
EngineWTuning.prototype.ecus = undefined;

/**
 * List of TCU's used in this engine.
 * @member {Array.<module:model/EngineTcu>} tcus
 */
EngineWTuning.prototype.tcus = undefined;

/**
 * @member {module:model/EnginePerformance} performance
 */
EngineWTuning.prototype.performance = undefined;

/**
 * @member {module:model/EngineTuning} tuning
 */
EngineWTuning.prototype.tuning = undefined;

