/*
 * RemapDB REST API Documentation
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains. 
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import EnginePerformanceDyno from './EnginePerformanceDyno';

/**
 * The EngineStagePerformance model module.
 * @module model/EngineStagePerformance
 * @version 1
 */
export default class EngineStagePerformance {
  /**
   * Constructs a new <code>EngineStagePerformance</code>.
   * Tuning/Remap stage performance object
   * @alias module:model/EngineStagePerformance
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EngineStagePerformance</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EngineStagePerformance} obj Optional instance to populate.
   * @return {module:model/EngineStagePerformance} The populated <code>EngineStagePerformance</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EngineStagePerformance();
      if (data.hasOwnProperty('power'))
        obj.power = ApiClient.convertToType(data['power'], 'Number');
      if (data.hasOwnProperty('torque'))
        obj.torque = ApiClient.convertToType(data['torque'], 'Number');
      if (data.hasOwnProperty('top_speed'))
        obj.topSpeed = ApiClient.convertToType(data['top_speed'], 'Number');
      if (data.hasOwnProperty('zero_to_hundred'))
        obj.zeroToHundred = ApiClient.convertToType(data['zero_to_hundred'], 'Number');
      if (data.hasOwnProperty('dyno_values'))
        obj.dynoValues = EnginePerformanceDyno.constructFromObject(data['dyno_values']);
    }
    return obj;
  }
}

/**
 * Horse power (afrer remap) (metric).
 * @member {Number} power
 */
EngineStagePerformance.prototype.power = undefined;

/**
 * Torque (after remap) in Nm.
 * @member {Number} torque
 */
EngineStagePerformance.prototype.torque = undefined;

/**
 * Maximum speed (kmh).
 * @member {Number} topSpeed
 */
EngineStagePerformance.prototype.topSpeed = undefined;

/**
 * Time to get from 0kmh to 100kmh (in seconds).
 * @member {Number} zeroToHundred
 */
EngineStagePerformance.prototype.zeroToHundred = undefined;

/**
 * @member {module:model/EnginePerformanceDyno} dynoValues
 */
EngineStagePerformance.prototype.dynoValues = undefined;

