/*
 * RemapDB REST API Documentation
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains. 
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ManufacturerModel from './ManufacturerModel';
import VehicleTypeShort from './VehicleTypeShort';

/**
 * The ManufacturerWModels model module.
 * @module model/ManufacturerWModels
 * @version 1
 */
export default class ManufacturerWModels {
  /**
   * Constructs a new <code>ManufacturerWModels</code>.
   * Manufacturer metadata object
   * @alias module:model/ManufacturerWModels
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ManufacturerWModels</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ManufacturerWModels} obj Optional instance to populate.
   * @return {module:model/ManufacturerWModels} The populated <code>ManufacturerWModels</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ManufacturerWModels();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('logo'))
        obj.logo = ApiClient.convertToType(data['logo'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = VehicleTypeShort.constructFromObject(data['type']);
      if (data.hasOwnProperty('models'))
        obj.models = ApiClient.convertToType(data['models'], [ManufacturerModel]);
    }
    return obj;
  }
}

/**
 * Manufacturer ID.
 * @member {Number} id
 */
ManufacturerWModels.prototype.id = undefined;

/**
 * Name of the manufacturer.
 * @member {String} name
 */
ManufacturerWModels.prototype.name = undefined;

/**
 * URL-friendly name (slug).
 * @member {String} slug
 */
ManufacturerWModels.prototype.slug = undefined;

/**
 * Link to manufacturer's logo.
 * @member {String} logo
 */
ManufacturerWModels.prototype.logo = undefined;

/**
 * @member {module:model/VehicleTypeShort} type
 */
ManufacturerWModels.prototype.type = undefined;

/**
 * List with all the models.
 * @member {Array.<module:model/ManufacturerModel>} models
 */
ManufacturerWModels.prototype.models = undefined;

