/*
 * RemapDB REST API Documentation
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains. 
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ManufacturerType from './ManufacturerType';

/**
 * The Manufacturer model module.
 * @module model/Manufacturer
 * @version 1
 */
export default class Manufacturer {
  /**
   * Constructs a new <code>Manufacturer</code>.
   * Manufacturer object
   * @alias module:model/Manufacturer
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Manufacturer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Manufacturer} obj Optional instance to populate.
   * @return {module:model/Manufacturer} The populated <code>Manufacturer</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Manufacturer();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('logo'))
        obj.logo = ApiClient.convertToType(data['logo'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ManufacturerType.constructFromObject(data['type']);
    }
    return obj;
  }
}

/**
 * Manufacturer ID.
 * @member {Number} id
 */
Manufacturer.prototype.id = undefined;

/**
 * Name of the manufacturer.
 * @member {String} name
 */
Manufacturer.prototype.name = undefined;

/**
 * URL-friendly name (slug).
 * @member {String} slug
 */
Manufacturer.prototype.slug = undefined;

/**
 * Link to manufacturer's logo.
 * @member {String} logo
 */
Manufacturer.prototype.logo = undefined;

/**
 * @member {module:model/ManufacturerType} type
 */
Manufacturer.prototype.type = undefined;

