/*
 * RemapDB REST API Documentation
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains. 
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ManufacturerShort from './ManufacturerShort';
import ModelShort from './ModelShort';
import VehicleTypeShort from './VehicleTypeShort';

/**
 * The ModelGeneration model module.
 * @module model/ModelGeneration
 * @version 1.0
 */
export default class ModelGeneration {
  /**
   * Constructs a new <code>ModelGeneration</code>.
   * Generation object
   * @alias module:model/ModelGeneration
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ModelGeneration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ModelGeneration} obj Optional instance to populate.
   * @return {module:model/ModelGeneration} The populated <code>ModelGeneration</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ModelGeneration();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('year'))
        obj.year = ApiClient.convertToType(data['year'], 'Number');
      if (data.hasOwnProperty('year_end'))
        obj.yearEnd = ApiClient.convertToType(data['year_end'], 'Number');
      if (data.hasOwnProperty('photo'))
        obj.photo = ApiClient.convertToType(data['photo'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = VehicleTypeShort.constructFromObject(data['type']);
      if (data.hasOwnProperty('manufacturer'))
        obj.manufacturer = ManufacturerShort.constructFromObject(data['manufacturer']);
      if (data.hasOwnProperty('model'))
        obj.model = ModelShort.constructFromObject(data['model']);
    }
    return obj;
  }
}

/**
 * Generation ID.
 * @member {Number} id
 */
ModelGeneration.prototype.id = undefined;

/**
 * Generation Name.
 * @member {String} name
 */
ModelGeneration.prototype.name = undefined;

/**
 * URL-friendly name (slug).
 * @member {String} slug
 */
ModelGeneration.prototype.slug = undefined;

/**
 * Year of manufacture.
 * @member {Number} year
 */
ModelGeneration.prototype.year = undefined;

/**
 * End year of manufacture.
 * @member {Number} yearEnd
 */
ModelGeneration.prototype.yearEnd = undefined;

/**
 * Link to generations's photo.
 * @member {String} photo
 */
ModelGeneration.prototype.photo = undefined;

/**
 * @member {module:model/VehicleTypeShort} type
 */
ModelGeneration.prototype.type = undefined;

/**
 * @member {module:model/ManufacturerShort} manufacturer
 */
ModelGeneration.prototype.manufacturer = undefined;

/**
 * @member {module:model/ModelShort} model
 */
ModelGeneration.prototype.model = undefined;

