/*
 * RemapDB REST API Documentation
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains. 
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import EngineShort from './EngineShort';
import GenerationShort from './GenerationShort';
import ManufacturerShort from './ManufacturerShort';
import ModelShort from './ModelShort';
import VehicleTypeShort from './VehicleTypeShort';

/**
 * The SearchResult model module.
 * @module model/SearchResult
 * @version 1.0
 */
export default class SearchResult {
  /**
   * Constructs a new <code>SearchResult</code>.
   * Search result object
   * @alias module:model/SearchResult
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SearchResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchResult} obj Optional instance to populate.
   * @return {module:model/SearchResult} The populated <code>SearchResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SearchResult();
      if (data.hasOwnProperty('type'))
        obj.type = VehicleTypeShort.constructFromObject(data['type']);
      if (data.hasOwnProperty('manufacturer'))
        obj.manufacturer = ManufacturerShort.constructFromObject(data['manufacturer']);
      if (data.hasOwnProperty('model'))
        obj.model = ModelShort.constructFromObject(data['model']);
      if (data.hasOwnProperty('generation'))
        obj.generation = GenerationShort.constructFromObject(data['generation']);
      if (data.hasOwnProperty('engine'))
        obj.engine = EngineShort.constructFromObject(data['engine']);
    }
    return obj;
  }
}

/**
 * @member {module:model/VehicleTypeShort} type
 */
SearchResult.prototype.type = undefined;

/**
 * @member {module:model/ManufacturerShort} manufacturer
 */
SearchResult.prototype.manufacturer = undefined;

/**
 * @member {module:model/ModelShort} model
 */
SearchResult.prototype.model = undefined;

/**
 * @member {module:model/GenerationShort} generation
 */
SearchResult.prototype.generation = undefined;

/**
 * @member {module:model/EngineShort} engine
 */
SearchResult.prototype.engine = undefined;

