/*
 * RemapDB REST API Documentation
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains. 
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import AccessScope from './AccessScope';
import SubscriptionSubscription from './SubscriptionSubscription';

/**
 * The Subscription model module.
 * @module model/Subscription
 * @version 1
 */
export default class Subscription {
  /**
   * Constructs a new <code>Subscription</code>.
   * @alias module:model/Subscription
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Subscription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Subscription} obj Optional instance to populate.
   * @return {module:model/Subscription} The populated <code>Subscription</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Subscription();
      if (data.hasOwnProperty('api_key'))
        obj.apiKey = ApiClient.convertToType(data['api_key'], 'String');
      if (data.hasOwnProperty('scopes'))
        obj.scopes = ApiClient.convertToType(data['scopes'], [AccessScope]);
      if (data.hasOwnProperty('calls_limit'))
        obj.callsLimit = ApiClient.convertToType(data['calls_limit'], 'Number');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('subscription'))
        obj.subscription = SubscriptionSubscription.constructFromObject(data['subscription']);
    }
    return obj;
  }
}

/**
 * The API Key used for the request.
 * @member {String} apiKey
 */
Subscription.prototype.apiKey = undefined;

/**
 * Array with strings. Contains all the access scopes that this API key has.
 * @member {Array.<module:model/AccessScope>} scopes
 */
Subscription.prototype.scopes = undefined;

/**
 * The maximum number of API requests that can be made within 1 hour.
 * @member {Number} callsLimit
 */
Subscription.prototype.callsLimit = undefined;

/**
 * ISO 8601 date
 * @member {Date} created
 */
Subscription.prototype.created = undefined;

/**
 * @member {module:model/SubscriptionSubscription} subscription
 */
Subscription.prototype.subscription = undefined;

