/*
 * RemapDB REST API Documentation
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains. 
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SubscriptionSubscription model module.
 * @module model/SubscriptionSubscription
 * @version 1.0
 */
export default class SubscriptionSubscription {
  /**
   * Constructs a new <code>SubscriptionSubscription</code>.
   * Object which contains the subscription information.
   * @alias module:model/SubscriptionSubscription
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SubscriptionSubscription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubscriptionSubscription} obj Optional instance to populate.
   * @return {module:model/SubscriptionSubscription} The populated <code>SubscriptionSubscription</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubscriptionSubscription();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('start_date'))
        obj.startDate = ApiClient.convertToType(data['start_date'], 'Date');
      if (data.hasOwnProperty('end_date'))
        obj.endDate = ApiClient.convertToType(data['end_date'], 'Date');
      if (data.hasOwnProperty('api_access'))
        obj.apiAccess = ApiClient.convertToType(data['api_access'], 'Boolean');
      if (data.hasOwnProperty('is_active'))
        obj.isActive = ApiClient.convertToType(data['is_active'], 'Boolean');
    }
    return obj;
  }
}

/**
 * Subscription ID
 * @member {Number} id
 */
SubscriptionSubscription.prototype.id = undefined;

/**
 * Date when subscription started. ISO 8601 format.
 * @member {Date} startDate
 */
SubscriptionSubscription.prototype.startDate = undefined;

/**
 * Subscription end date. ISO 8601 format.
 * @member {Date} endDate
 */
SubscriptionSubscription.prototype.endDate = undefined;

/**
 * Can this subscription access the API.
 * @member {Boolean} apiAccess
 */
SubscriptionSubscription.prototype.apiAccess = undefined;

/**
 * Shows if description is active or not.
 * @member {Boolean} isActive
 */
SubscriptionSubscription.prototype.isActive = undefined;

