/*
 * RemapDB REST API Documentation
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains. 
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import Error from '../model/Error';
import GenerationWEngines from '../model/GenerationWEngines';
import ModelGeneration from '../model/ModelGeneration';

/**
* Generations service.
* @module api/GenerationsApi
* @version 1.0
*/
export default class GenerationsApi {

    /**
    * Constructs a new GenerationsApi. 
    * @alias module:api/GenerationsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getGeneration operation.
     * @callback moduleapi/GenerationsApi~getGenerationCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GenerationWEngines{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Show all generation metadata along with its corresponding engines
     * Show all generation metadata along with its corresponding engines.
     * @param {Number} generationId Generation ID.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.acceptLanguage Method accept custom language. Content of the header should be the code of the language you are requesting. E.g.: &#x60;en&#x60;. 
     * @param {module:api/GenerationsApi~getGenerationCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getGeneration(generationId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'generationId' is set
      if (generationId === undefined || generationId === null) {
        throw new Error("Missing the required parameter 'generationId' when calling getGeneration");
      }

      let pathParams = {
        'generation_id': generationId
      };
      let queryParams = {
        
      };
      let headerParams = {
        'Accept-Language': opts['acceptLanguage']
      };
      let formParams = {
        
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GenerationWEngines;

      return this.apiClient.callApi(
        '/generations/{generation_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the listGenerations operation.
     * @callback moduleapi/GenerationsApi~listGenerationsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ModelGeneration>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Show all generations from specific model
     * Show all generations from specific model.
     * @param {Number} modelId Model ID.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.acceptLanguage Method accept custom language. Content of the header should be the code of the language you are requesting. E.g.: &#x60;en&#x60;. 
     * @param {module:api/GenerationsApi~listGenerationsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    listGenerations(modelId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'modelId' is set
      if (modelId === undefined || modelId === null) {
        throw new Error("Missing the required parameter 'modelId' when calling listGenerations");
      }

      let pathParams = {
        'model_id': modelId
      };
      let queryParams = {
        
      };
      let headerParams = {
        'Accept-Language': opts['acceptLanguage']
      };
      let formParams = {
        
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ModelGeneration];

      return this.apiClient.callApi(
        '/generations/model/{model_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}