/*
 * RemapDB REST API Documentation
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains. 
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import Error from '../model/Error';
import Manufacturer from '../model/Manufacturer';
import ManufacturerWModels from '../model/ManufacturerWModels';

/**
* Manufacturers service.
* @module api/ManufacturersApi
* @version 1
*/
export default class ManufacturersApi {

    /**
    * Constructs a new ManufacturersApi. 
    * @alias module:api/ManufacturersApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getManufacturer operation.
     * @callback moduleapi/ManufacturersApi~getManufacturerCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ManufacturerWModels{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Show all manufacturer metadata along with its corresponding models
     * Show all manufacturer metadata along with its corresponding models.
     * @param {Number} manufacturerId Manufacturer ID.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.acceptLanguage Method accept custom language. Content of the header should be the code of the language you are requesting. E.g.: &#x60;en&#x60;. 
     * @param {module:api/ManufacturersApi~getManufacturerCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getManufacturer(manufacturerId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'manufacturerId' is set
      if (manufacturerId === undefined || manufacturerId === null) {
        throw new Error("Missing the required parameter 'manufacturerId' when calling getManufacturer");
      }

      let pathParams = {
        'manufacturer_id': manufacturerId
      };
      let queryParams = {
        
      };
      let headerParams = {
        'Accept-Language': opts['acceptLanguage']
      };
      let formParams = {
        
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ManufacturerWModels;

      return this.apiClient.callApi(
        '/manufacturers/{manufacturer_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the listManufacturers operation.
     * @callback moduleapi/ManufacturersApi~listManufacturersCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Manufacturer>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Show all manufacturers from specific type
     * Show all manufacturers from specific type.
     * @param {Number} typeId Vehicle type ID.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.acceptLanguage Method accept custom language. Content of the header should be the code of the language you are requesting. E.g.: &#x60;en&#x60;. 
     * @param {module:api/ManufacturersApi~listManufacturersCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    listManufacturers(typeId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'typeId' is set
      if (typeId === undefined || typeId === null) {
        throw new Error("Missing the required parameter 'typeId' when calling listManufacturers");
      }

      let pathParams = {
        'type_id': typeId
      };
      let queryParams = {
        
      };
      let headerParams = {
        'Accept-Language': opts['acceptLanguage']
      };
      let formParams = {
        
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Manufacturer];

      return this.apiClient.callApi(
        '/manufacturers/type/{type_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}