/*
 * RemapDB REST API Documentation
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains. 
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import Error from '../model/Error';
import ManufacturerModel from '../model/ManufacturerModel';
import ModelWGenerations from '../model/ModelWGenerations';

/**
* Models service.
* @module api/ModelsApi
* @version 1.0
*/
export default class ModelsApi {

    /**
    * Constructs a new ModelsApi. 
    * @alias module:api/ModelsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the getModel operation.
     * @callback moduleapi/ModelsApi~getModelCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ModelWGenerations{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Show all model metadata along with its corresponding generations
     * Show all model metadata along with its corresponding generations.
     * @param {Number} modelId Model ID.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.acceptLanguage Method accept custom language. Content of the header should be the code of the language you are requesting. E.g.: &#x60;en&#x60;. 
     * @param {module:api/ModelsApi~getModelCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getModel(modelId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'modelId' is set
      if (modelId === undefined || modelId === null) {
        throw new Error("Missing the required parameter 'modelId' when calling getModel");
      }

      let pathParams = {
        'model_id': modelId
      };
      let queryParams = {
        
      };
      let headerParams = {
        'Accept-Language': opts['acceptLanguage']
      };
      let formParams = {
        
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ModelWGenerations;

      return this.apiClient.callApi(
        '/models/{model_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the listModels operation.
     * @callback moduleapi/ModelsApi~listModelsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/ManufacturerModel>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Show all models from specific manufacturer
     * Show all models from specific manufacturer.
     * @param {Number} manufacturerId Manufacturer ID.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.acceptLanguage Method accept custom language. Content of the header should be the code of the language you are requesting. E.g.: &#x60;en&#x60;. 
     * @param {module:api/ModelsApi~listModelsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    listModels(manufacturerId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'manufacturerId' is set
      if (manufacturerId === undefined || manufacturerId === null) {
        throw new Error("Missing the required parameter 'manufacturerId' when calling listModels");
      }

      let pathParams = {
        'manufacturer_id': manufacturerId
      };
      let queryParams = {
        
      };
      let headerParams = {
        'Accept-Language': opts['acceptLanguage']
      };
      let formParams = {
        
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [ManufacturerModel];

      return this.apiClient.callApi(
        '/models/manufacturer/{manufacturer_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}