/*
 * RemapDB REST API Documentation
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains. 
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from "../ApiClient";
import Error from '../model/Error';
import VehicleType from '../model/VehicleType';

/**
* Types service.
* @module api/TypesApi
* @version 1.0
*/
export default class TypesApi {

    /**
    * Constructs a new TypesApi. 
    * @alias module:api/TypesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the listTypes operation.
     * @callback moduleapi/TypesApi~listTypesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/VehicleType>{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Show vehicle types
     * Provides a list of all available vehicle types.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.acceptLanguage Method accept custom language. Content of the header should be the code of the language you are requesting. E.g.: &#x60;en&#x60;. 
     * @param {module:api/TypesApi~listTypesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    listTypes(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        'Accept-Language': opts['acceptLanguage']
      };
      let formParams = {
        
      };

      let authNames = ['api_key'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [VehicleType];

      return this.apiClient.callApi(
        '/types', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}