/*
 * RemapDB REST API Documentation
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains. 
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RemapdbJsSdk);
  }
}(this, function(expect, RemapdbJsSdk) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('EngineTuning', function() {
      beforeEach(function() {
        instance = new RemapdbJsSdk.EngineTuning();
      });

      it('should create an instance of EngineTuning', function() {
        // TODO: update the code to test EngineTuning
        expect(instance).to.be.a(RemapdbJsSdk.EngineTuning);
      });

      it('should have the property options (base name: "options")', function() {
        // TODO: update the code to test the property options
        expect(instance).to.have.property('options');
        // expect(instance.options).to.be(expectedValueLiteral);
      });

      it('should have the property readTools (base name: "read_tools")', function() {
        // TODO: update the code to test the property readTools
        expect(instance).to.have.property('readTools');
        // expect(instance.readTools).to.be(expectedValueLiteral);
      });

      it('should have the property workMethods (base name: "work_methods")', function() {
        // TODO: update the code to test the property workMethods
        expect(instance).to.have.property('workMethods');
        // expect(instance.workMethods).to.be(expectedValueLiteral);
      });

      it('should have the property stages (base name: "stages")', function() {
        // TODO: update the code to test the property stages
        expect(instance).to.have.property('stages');
        // expect(instance.stages).to.be(expectedValueLiteral);
      });

    });
  });

}));
