/*
 * RemapDB REST API Documentation
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains. 
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.RemapdbJsSdk);
  }
}(this, function(expect, RemapdbJsSdk) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('EnginePerformanceDyno', function() {
      beforeEach(function() {
        instance = new RemapdbJsSdk.EnginePerformanceDyno();
      });

      it('should create an instance of EnginePerformanceDyno', function() {
        // TODO: update the code to test EnginePerformanceDyno
        expect(instance).to.be.a(RemapdbJsSdk.EnginePerformanceDyno);
      });

      it('should have the property rpm (base name: "rpm")', function() {
        // TODO: update the code to test the property rpm
        expect(instance).to.have.property('rpm');
        // expect(instance.rpm).to.be(expectedValueLiteral);
      });

      it('should have the property hp (base name: "hp")', function() {
        // TODO: update the code to test the property hp
        expect(instance).to.have.property('hp');
        // expect(instance.hp).to.be(expectedValueLiteral);
      });

      it('should have the property nm (base name: "nm")', function() {
        // TODO: update the code to test the property nm
        expect(instance).to.have.property('nm');
        // expect(instance.nm).to.be(expectedValueLiteral);
      });

    });
  });

}));
