/*
 * RemapDB REST API Documentation
 * Vehicle Tuning Database API - For Tuning services and Tuners.  Access comprehensive vehicle details, including types, manufacturers, models, engines, ECU and TCU info, tuning tools, dyno charts, and available tuning or remap stages with their performance gains. 
 *
 * OpenAPI spec version: 1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.64
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import AccessScope from './model/AccessScope';
import Engine from './model/Engine';
import EngineEcu from './model/EngineEcu';
import EnginePerformance from './model/EnginePerformance';
import EnginePerformanceDyno from './model/EnginePerformanceDyno';
import EngineShort from './model/EngineShort';
import EngineStage from './model/EngineStage';
import EngineStagePerformance from './model/EngineStagePerformance';
import EngineTcu from './model/EngineTcu';
import EngineTuning from './model/EngineTuning';
import EngineWTuning from './model/EngineWTuning';
import Error from './model/Error';
import GenerationShort from './model/GenerationShort';
import GenerationWEngines from './model/GenerationWEngines';
import InlineResponse200 from './model/InlineResponse200';
import Manufacturer from './model/Manufacturer';
import ManufacturerModel from './model/ManufacturerModel';
import ManufacturerShort from './model/ManufacturerShort';
import ManufacturerType from './model/ManufacturerType';
import ManufacturerWModels from './model/ManufacturerWModels';
import ModelGeneration from './model/ModelGeneration';
import ModelShort from './model/ModelShort';
import ModelWGenerations from './model/ModelWGenerations';
import ReadTool from './model/ReadTool';
import SearchResult from './model/SearchResult';
import Subscription from './model/Subscription';
import SubscriptionSubscription from './model/SubscriptionSubscription';
import TuningOption from './model/TuningOption';
import VehicleType from './model/VehicleType';
import VehicleTypeShort from './model/VehicleTypeShort';
import WorkMethod from './model/WorkMethod';
import EnginesApi from './api/EnginesApi';
import GenerationsApi from './api/GenerationsApi';
import ManufacturersApi from './api/ManufacturersApi';
import ModelsApi from './api/ModelsApi';
import SearchApi from './api/SearchApi';
import SubscriptionApi from './api/SubscriptionApi';
import TypesApi from './api/TypesApi';

/**
* RemapDB.com - Vehicle Tuning Database API .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var RemapdbJsSdk = require('index'); // See note below*.
* var xxxSvc = new RemapdbJsSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new RemapdbJsSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new RemapdbJsSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new RemapdbJsSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AccessScope model constructor.
     * @property {module:model/AccessScope}
     */
    AccessScope,

    /**
     * The Engine model constructor.
     * @property {module:model/Engine}
     */
    Engine,

    /**
     * The EngineEcu model constructor.
     * @property {module:model/EngineEcu}
     */
    EngineEcu,

    /**
     * The EnginePerformance model constructor.
     * @property {module:model/EnginePerformance}
     */
    EnginePerformance,

    /**
     * The EnginePerformanceDyno model constructor.
     * @property {module:model/EnginePerformanceDyno}
     */
    EnginePerformanceDyno,

    /**
     * The EngineShort model constructor.
     * @property {module:model/EngineShort}
     */
    EngineShort,

    /**
     * The EngineStage model constructor.
     * @property {module:model/EngineStage}
     */
    EngineStage,

    /**
     * The EngineStagePerformance model constructor.
     * @property {module:model/EngineStagePerformance}
     */
    EngineStagePerformance,

    /**
     * The EngineTcu model constructor.
     * @property {module:model/EngineTcu}
     */
    EngineTcu,

    /**
     * The EngineTuning model constructor.
     * @property {module:model/EngineTuning}
     */
    EngineTuning,

    /**
     * The EngineWTuning model constructor.
     * @property {module:model/EngineWTuning}
     */
    EngineWTuning,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The GenerationShort model constructor.
     * @property {module:model/GenerationShort}
     */
    GenerationShort,

    /**
     * The GenerationWEngines model constructor.
     * @property {module:model/GenerationWEngines}
     */
    GenerationWEngines,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The Manufacturer model constructor.
     * @property {module:model/Manufacturer}
     */
    Manufacturer,

    /**
     * The ManufacturerModel model constructor.
     * @property {module:model/ManufacturerModel}
     */
    ManufacturerModel,

    /**
     * The ManufacturerShort model constructor.
     * @property {module:model/ManufacturerShort}
     */
    ManufacturerShort,

    /**
     * The ManufacturerType model constructor.
     * @property {module:model/ManufacturerType}
     */
    ManufacturerType,

    /**
     * The ManufacturerWModels model constructor.
     * @property {module:model/ManufacturerWModels}
     */
    ManufacturerWModels,

    /**
     * The ModelGeneration model constructor.
     * @property {module:model/ModelGeneration}
     */
    ModelGeneration,

    /**
     * The ModelShort model constructor.
     * @property {module:model/ModelShort}
     */
    ModelShort,

    /**
     * The ModelWGenerations model constructor.
     * @property {module:model/ModelWGenerations}
     */
    ModelWGenerations,

    /**
     * The ReadTool model constructor.
     * @property {module:model/ReadTool}
     */
    ReadTool,

    /**
     * The SearchResult model constructor.
     * @property {module:model/SearchResult}
     */
    SearchResult,

    /**
     * The Subscription model constructor.
     * @property {module:model/Subscription}
     */
    Subscription,

    /**
     * The SubscriptionSubscription model constructor.
     * @property {module:model/SubscriptionSubscription}
     */
    SubscriptionSubscription,

    /**
     * The TuningOption model constructor.
     * @property {module:model/TuningOption}
     */
    TuningOption,

    /**
     * The VehicleType model constructor.
     * @property {module:model/VehicleType}
     */
    VehicleType,

    /**
     * The VehicleTypeShort model constructor.
     * @property {module:model/VehicleTypeShort}
     */
    VehicleTypeShort,

    /**
     * The WorkMethod model constructor.
     * @property {module:model/WorkMethod}
     */
    WorkMethod,

    /**
    * The EnginesApi service constructor.
    * @property {module:api/EnginesApi}
    */
    EnginesApi,

    /**
    * The GenerationsApi service constructor.
    * @property {module:api/GenerationsApi}
    */
    GenerationsApi,

    /**
    * The ManufacturersApi service constructor.
    * @property {module:api/ManufacturersApi}
    */
    ManufacturersApi,

    /**
    * The ModelsApi service constructor.
    * @property {module:api/ModelsApi}
    */
    ModelsApi,

    /**
    * The SearchApi service constructor.
    * @property {module:api/SearchApi}
    */
    SearchApi,

    /**
    * The SubscriptionApi service constructor.
    * @property {module:api/SubscriptionApi}
    */
    SubscriptionApi,

    /**
    * The TypesApi service constructor.
    * @property {module:api/TypesApi}
    */
    TypesApi
};
